DELETE FROM REPRESENTANTE;

DELETE FROM COLONO;

DELETE FROM ACTIVIDADE_MONITOR;

DELETE FROM ACTIVIDADE_EQUIPA;
DELETE FROM EQUIPA;
DELETE FROM MONITOR;

DELETE FROM ACTIVIDADE_DESPORTIVA;
DELETE FROM CONTACTO;
DELETE FROM PESSOA;
DELETE FROM GRUPO;
DELETE FROM CAMPOFERIAS;
DELETE FROM ACTIVIDADE;
