DROP TABLE IF EXISTS REPRESENTANTE;

DROP TABLE IF EXISTS COLONO;

DROP TABLE IF EXISTS ACTIVIDADE_MONITOR;


DROP TABLE IF EXISTS ACTIVIDADE_EQUIPA;
DROP TABLE IF EXISTS EQUIPA;
DROP TABLE IF EXISTS MONITOR;

DROP TABLE IF EXISTS ACTIVIDADE_DESPORTIVA;
DROP TABLE IF EXISTS CONTACTO;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS GRUPO;
DROP TABLE IF EXISTS CAMPOFERIAS;
DROP TABLE IF EXISTS ACTIVIDADE;

